spring:
  application:
    name: estudiantes-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/veterinaria_db
    username: vet_user
    password: vet_password
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

server:
  port: 8085

