spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/auth/**
        - id: mascotas-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/mascotas/**
        - id: propietarios-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/propietarios/**
        - id: citas-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/citas/**
        - id: notificaciones-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notificaciones/**
        - id: estudiantes-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/estudiantes/**
        - id: historia-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/historias/**
        - id: prescripciones-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/prescripciones/**
        - id: inventario-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/inventario/**
        - id: pagos-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/facturacion/**
        - id: servicios-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/servicios/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

